version: '3.8'
services:
  openldap:
    image: osixia/openldap:1.4.0
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - "./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom"
    command: --copy-service --loglevel debug
  phonebook:
    build: .
    depends_on:
      - "openldap"
    ports:
      - "8080:8080"